config/routes.rb
Rails.application.routes.draw do
#rootパス
root 'homes#top'

#userのdevise
devise_for :users, controllers: {
  registrations: 'users/registrations',
  passwords: 'users/passwords',
  sessions: 'users/sessions',
  omniauth_callbacks: 'users/omniauth_callbacks'}

get 'homes/top' => 'homes#top', as: 'user_top'
get 'homes/about' => 'homes#about', as: 'user_about'
resources :users, only: [:show, :edit, :update]
  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'user_unsubscribe'
  patch 'users/:id/unsubscribe' => 'users#unsubscribe_done', as: 'user_unsubscribe_done'
  put '/users/:id/unsubscribe' => 'users#unsubscribe_done', as: 'users_unsubscribe_done'

resources :items do
  get 'search' => 'searches#search', as: 'search'
    member do
      get :download
    end
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
end

get  'contacts/index' =>'contacts#index'
post 'contacts/confirm' => 'contacts#confirm'
post 'contacts/done' => 'contacts#done'


# 管理者用サイトのrouting
devise_scope :admins do
	devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    passwords: 'admins/passwords',
    sessions: 'admins/sessions'}
end

namespace :admins do
	get 'homes/top' => 'homes#top', as:'top'
	resources :users, only: [:index, :edit, :show, :update]

    get 'search' => 'searches#search', as: 'search'
end

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  attachment :image

  has_many :items
  has_many :comments
  has_many :likes

  validates :email, presence: true
  validates :name, presence: true
  validates :username, presence: true

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        name:     auth.info.email,
        username: auth.info.email,
        password: Devise.friendly_token[0, 20]
      )
    end

    user
  end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController

  def edit
  	@user = User.find(params[:id])
  end

  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "会員情報が更新されました"
       redirect_to admins_user_path(@user)
    else
      flash[:notice] = "会員情報の更新ができませんでした"
      render :edit
    end
  end


  private

  def user_params
	params.require(:user).permit(:is_status, :name, :username, :image, :uid, :provider, :email, :audio)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def facebook
    callback_from :facebook
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to items_path
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user
    before_action :baria_user, only: [:edit,:update,:unsubscribe]


  def edit
  	@user = User.find(params[:id])
  end

  def show
  	@user = User.find(params[:id])
  end

  def unsubscribe
  end

  def update
  	@user = User.find(params[:id])
  	if
  	  @user.update(user_params)
  	  redirect_to user_path(@user.id)
  	else
  	  render "edit"
  	end
  end


private

def set_user
	@user = User.find(params[:id])
end

def user_params
	params.require(:user).permit(:is_status, :name, :username, :image, :uid, :provider, :email, :audio)
end

#url直接防止　メソッドを自己定義してbefore_actionで発動。
  def baria_user
    unless params[:id].to_i == current_user.id
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render 'layouts/logo' %>
<div class='container'>
  <div class='row'>
    <%= render 'items/sidebar' %>
    <div class="main">
      <div class="col-sm-7">
        <h2>登録情報編集</h2><br><br>

        <div class="row">
          <%= form_for @user,url: {action: "update"} do |f| %>
            <div class="col-sm-1"></div>
            <div class="col-sm-4">
              <%= attachment_image_tag @user, :image, size: "200x200",  fallback: "no_image.jpg"%><br>
              <%= f.attachment_field :image %>
            </div>

            <div class="col-xs-1"></div>
            <div class="col-xs-6">
              <div class='form-group row'>
                <div class='col-lg-5'>
                  <h5><%= f.label :ユーザーネーム %></h5>
                </div>
                <div class='col-lg-7'>
                  <span style='display: inline-block;'>
                    <%= f.text_field :username, autofocus: true, autocomplete: 'username', class: 'form-control' %>
                  </span>
                </div>
              </div>

              <div class='form-group row'>
                <div class='col-lg-5'>
                  <h5><%= f.label :メールアドレス %></h5>
                </div>
                <div class='col-lg-7'>
                  <span style='display: inline-block;'>
                    <%= f.text_field :email, autofocus: true, autocomplete: 'email', class: 'form-control' %>
                  </span>
                </div>
              </div>
            </div>

            <div class="formgroup row">
              <div class="col-lg-7"></div>
              <div class="col-lg-3">
                <%= f.submit '編集内容を保存する', class:'btn btn-success' %>
              </div>
              <div class="col-lg-2">
                <%= link_to "パスワード変更", edit_user_registration_path, class: 'btn btn-warning' %>
              </div>
            </div><br><br>
            <div class ="row">
              <div class="col-lg-10"></div>
              <div class="col-lg-1">
                <%= link_to '退会する', user_unsubscribe_path, class:'btn btn-danger'  %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'layouts/logo' %>
<div class="container">
  <div class="row">
    <%= render 'items/sidebar' %>
    <div class="main">
      <div class="col-sm-10">
  	    <h2>マイページ</h2>

  	<!-- 会員情報　-->
  	    <div class="col-sm-1"></div>
  	    <div class="col-sm-3">
  	      <figure class="box">
  	  	    <%= attachment_image_tag @user, :image, size: "200x200", fallback: "no_image.jpg" %>
  	      </figure>
  	    </div>
  	    <div class="col-sm-5">
  	      <table class="table">
  	  	    <tr>
  	  	      <th><h4>ユーザーネーム</h4></th>
  	  	      <td><%= @user.username %></td>
  	  	    </tr>
            
            <% if @user == current_user %>
  	  	    <tr>
  	  	      <th><h4>メールアドレス</h4></th>
  	  	      <td><%= @user.email %></td>
  	  	    </tr>
            <% end %>

            <tr>
              <th></th>
              <td></td>
            </tr>

  	      </table>
          <% if @user == current_user %>
            <%= link_to "編集", edit_user_path, class: "edit-btn" %><br><br>
          <% end %>
  	    </div>
      </div>
      <div class="col-sm-10">
        <div class="col-sm-1"></div>
        <div class="col-sm-8">
          <h3>投稿</h3><br><br>
          <% @user.items.each do |item|%>
            <div class="item-panel">
              <div class="item-image">
                <div class="row">
                  <span class="col-xs-3">
                    <%= attachment_image_tag item.user, :image, :fill, 60, 60, format: 'jpg',fallback: "no_image.jpg" ,size:'60x60'%>
                  </span>
                  <span class="col-xs-8">
                    <h7 class="item-name"><%= item.user.username %></h7>
                  </span>
                </div>
              </div>
              <div class="item-title">
                <div class="row">
                  <span class="col-xs-3">
                  </span>
                  <span class="col-xs-9">
                    <%= link_to item.title, item_path(item) %><br>
                  </span>
                </div>
              </div><br>
              <div class="item-link">
                <div class="row">
                  <span class="col-xs-3">
                  </span>
                  <span class="col-xs-2">
                    <i class="far fa-comments"></i> <%= item.comments.count %>
                  </span>
                  <span class="col-xs-2" id="likes_buttons_<%= item.id %>">
                    <%= render partial: "likes/like", locals: { item: item } %>
                  </span>
                  <span class="col-xs-2">
                    <%= link_to download_item_path(item), data: { turbolinks: false }, "data-confirm" => "音源をダウンロードしますか？" do %>
                      <i class="fas fa-arrow-alt-circle-down"></i>
                    <% end %>
                  </span>
                  <% if item.user_id == current_user.id %>
                  <span class="col-xs-2">
                    <%= link_to item_path(item), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
                      <i class="fas fa-trash-alt"></i>
                    <% end %>
                  </span>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/unsubscribe.html.erb
<%= render 'layouts/logo' %>
<div class="container" style="width:40%; margin: 50px auto";>
  <div class="row space">
    <h2>本当に退会しますか？</h2>
  </div>

  <div class="row space">
    <h4>退会すると、会員登録情報や
      <br>これまでの投稿が閲覧できなくなります。
      <br>退会する場合は「退会する」をクリックしてください。
    </h4>
  </div>

  <div class="row space">
    <%= link_to "退会しない",user_path(current_user),class: "btn btn-primary" %>
    <%= link_to "退会する", user_unsubscribe_done_path(current_user), method: :put, "data-confirm" => "本当に退会しますか？", class: "btn btn-danger" %>
  </div>
</div>