config/routes.rb
Rails.application.routes.draw do
#rootパス
root 'homes#top'

#userのdevise
devise_for :users, controllers: {
  registrations: 'users/registrations',
  passwords: 'users/passwords',
  sessions: 'users/sessions',
  omniauth_callbacks: 'users/omniauth_callbacks'}

get 'homes/top' => 'homes#top', as: 'user_top'
get 'homes/about' => 'homes#about', as: 'user_about'
resources :users, only: [:show, :edit, :update]
  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'user_unsubscribe'
  patch 'users/:id/unsubscribe' => 'users#unsubscribe_done', as: 'user_unsubscribe_done'
  put '/users/:id/unsubscribe' => 'users#unsubscribe_done', as: 'users_unsubscribe_done'

resources :items do
  get 'search' => 'searches#search', as: 'search'
    member do
      get :download
    end
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
end

get  'contacts/index' =>'contacts#index'
post 'contacts/confirm' => 'contacts#confirm'
post 'contacts/done' => 'contacts#done'


# 管理者用サイトのrouting
devise_scope :admins do
	devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    passwords: 'admins/passwords',
    sessions: 'admins/sessions'}
end

namespace :admins do
	get 'homes/top' => 'homes#top', as:'top'
	resources :users, only: [:index, :edit, :show, :update]

    get 'search' => 'searches#search', as: 'search'
end

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  attachment :image

  has_many :items
  has_many :comments
  has_many :likes

  validates :email, presence: true
  validates :name, presence: true
  validates :username, presence: true

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        name:     auth.info.email,
        username: auth.info.email,
        password: Devise.friendly_token[0, 20]
      )
    end

    user
  end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController

  def edit
  	@user = User.find(params[:id])
  end

  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "会員情報が更新されました"
       redirect_to admins_user_path(@user)
    else
      flash[:notice] = "会員情報の更新ができませんでした"
      render :edit
    end
  end


  private

  def user_params
	params.require(:user).permit(:is_status, :name, :username, :image, :uid, :provider, :email, :audio)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def facebook
    callback_from :facebook
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to items_path
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user
    before_action :baria_user, only: [:edit,:update,:unsubscribe]


  def edit
  	@user = User.find(params[:id])
  end

  def show
  	@user = User.find(params[:id])
  end

  def unsubscribe
  end

  def update
  	@user = User.find(params[:id])
  	if
  	  @user.update(user_params)
  	  redirect_to user_path(@user.id)
  	else
  	  render "edit"
  	end
  end


private

def set_user
	@user = User.find(params[:id])
end

def user_params
	params.require(:user).permit(:is_status, :name, :username, :image, :uid, :provider, :email, :audio)
end

#url直接防止　メソッドを自己定義してbefore_actionで発動。
  def baria_user
    unless params[:id].to_i == current_user.id
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/edit.html.erb
<div class="container">
    <div class="col-xs-10">
      <h2><i class="fas fa-user-edit"></i> 会員情報編集</h2>
    </div>

    <%= form_for(@user, url:admins_user_path, method: :patch) do |f| %>
    <div class='form-group row'>
      <div class='col-lg-4'>
        <h5><%= f.label :会員ステータス %></h5>
      </div>
      <div class='col-lg-2'>
        <% if @user.is_status? %>
          <td><span class="badge" style="background:#d72238;">退会済み</span></td>
        <% else %>
          <td><span class="badge" style="background:#8bce9a;">有効会員</span></td>
        <% end %>
      </div>
    </div>

    <div class='form-group row'>
      <div class='col-lg-4'>
        <h5><%= f.label :名前 %></h5>
      </div>
      <div class='col-lg-8'>
        <span style='display: inline-block;'>
          <%= f.text_field :name, autofocus: true, autocomplete: 'name', class: 'form-control' %>
        </span>
      </div>
    </div>
    
    <div class='form-group row'>
      <div class='col-lg-4'>
        <h5><%= f.label :ユーザーネーム %></h5>
      </div>
      <div class='col-lg-8'>
        <span style='display: inline-block;'>
          <%= f.text_field :username, autofocus: true, autocomplete: 'username', class: 'form-control' %>
        </span>
      </div>
    </div>

    <div class='form-group row'>
      <div class='col-lg-4'>
        <h5><%= f.label :メールアドレス %></h5>
      </div>
      <div class='col-lg-4'>
        <%= f.text_field :email, autofocus: true, autocomplete: 'email', class: 'form-control' %>
      </div>
    </div>



    <div class="form-group row">
      <div class="col-lg-4 offset-lg-8">
        <%= f.submit '編集内容を保存する', class:'btn btn-success' %>
      </div>
    </div>
    <% end %>
</div>

app/views/admins/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h2><i class="fas fa-user"></i> 会員一覧</h2>
      <br>
	    <!--会員一覧 -->
		  <table class="table table-hover">
		  	<thead>
		  	  <tr class="active">
		  	  	<th>ID</th>
		        <th>名前</th>
		        <th>ユーザーネーム</th>
		        <th>メールアドレス</th>
		        <th>ステータス</th>
		        <th></th>
		        <th></th>
	          </tr>
	        </thead>
	        <tbody>
              <% @users.each do |user| %>
			    <tr>
			      <td><%= user.id %></td>
			      <td><%= user.name %></td>
			      <td><%= user.username %></td>
			      <td><%= user.email %></td>
			      <% if user.is_status == false %>
                    <td><span class="badge" style="background:#8bce9a;">有効会員</span></td>
                  <% else %>
                    <td><span class="badge" style="background:#d72238;">退会済み</span></td>
                  <% end %>
		          <td><%= link_to "詳細", admins_user_path(user.id) ,class: "btn btn-primary" %></td>
		          <td><%= link_to "編集", edit_admins_user_path(user.id) ,class: "btn btn-success" %></td>
		        </tr>
			  <% end %>
		    </table>
	</div>
  </div>
</div>

app/views/admins/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10">
      <h2><i class="far fa-id-card"></i> 会員情報詳細</h2>

      <!-- 会員情報 -->
      <table class="table table-border">
        <tr>
          <th>会員ID</th>
          <td>
            <%= @user.id %>
            <% if @user.is_status? %>
              <span class="badge" style="background:#d72238;">退会済み</span>
            <% else %>
              <span class="badge" style="background:#8bce9a;">有効会員</span>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>名前</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th>ユーザーネーム</th>
          <td><%= @user.username %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th></th>
          <td><%= link_to "編集する", edit_admins_user_path(@user.id) ,class: "btn btn-success" %> <%= link_to "会員一覧にもどる", admins_users_path ,class: "btn btn-danger" %></td>
        </tr>
      </table>
    </div>
  </div>
</div>