config/routes.rb
Rails.application.routes.draw do
#rootパス
root 'homes#top'

#userのdevise
devise_for :users, controllers: {
  registrations: 'users/registrations',
  passwords: 'users/passwords',
  sessions: 'users/sessions',
  omniauth_callbacks: 'users/omniauth_callbacks'}

get 'homes/top' => 'homes#top', as: 'user_top'
get 'homes/about' => 'homes#about', as: 'user_about'
resources :users, only: [:show, :edit, :update]
  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'user_unsubscribe'
  patch 'users/:id/unsubscribe' => 'users#unsubscribe_done', as: 'user_unsubscribe_done'
  put '/users/:id/unsubscribe' => 'users#unsubscribe_done', as: 'users_unsubscribe_done'

resources :items do
  get 'search' => 'searches#search', as: 'search'
    member do
      get :download
    end
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
end

get  'contacts/index' =>'contacts#index'
post 'contacts/confirm' => 'contacts#confirm'
post 'contacts/done' => 'contacts#done'


# 管理者用サイトのrouting
devise_scope :admins do
	devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    passwords: 'admins/passwords',
    sessions: 'admins/sessions'}
end

namespace :admins do
	get 'homes/top' => 'homes#top', as:'top'
	resources :users, only: [:index, :edit, :show, :update]

    get 'search' => 'searches#search', as: 'search'
end

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/item.rb
class Item < ApplicationRecord
	mount_uploader :file, AudioFileUploader
	
	belongs_to :user
	has_many :likes, dependent: :destroy
	has_many :comments, dependent: :destroy
  has_many :item_tags, dependent: :destroy
  has_many :tags, through: :item_tags

  validates :title, presence: true
  validates :text, presence: true
  validates :file, presence: true

  default_scope -> { order(created_at: :desc) }

	def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search
      Item.where(['title LIKE ? OR text LIKE ?', "%#{search}%", "%#{search}%"])
    else
      Item.all
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def new
    @item = Item.new
  end

  def index
    @items = Item.all
    @item = Item.new
    @search_items = Item.all.page(params[:page]).search(params[:search])
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save!
       redirect_to items_path
    else
       render "new"
    end
  end

  def download
    @item = Item.find(params[:id])
    filepath = "https://rails-item1.s3-ap-northeast-1.amazonaws.com/"+@item.file.current_path
    data = open(URI.encode(filepath))
    send_data data.read, filename: @item.file.identifier, type: "application/wav", disposition: 'inline', stream: 'true', buffer_size: '40960'
  end


  def show
    @item = Item.find(params[:id])
    @newitem = Item.new
    @comment = Comment.new
    @search_items = Item.all.page(params[:page]).search(params[:search])
  end

  def edit
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:id,:user_id,:title,:text,:file,:audio,:serch, { :tag_ids=> [] })
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_search.html.erb
  <div class="col-lg-3">
    <div class="search">
    <%= form_tag(items_path, :method => "get") do %>
      <%= text_field_tag :search, params[:search], placeholder: "キーワード検索", class: "search-form" %>
      <%= submit_tag "検索", :name => nil %>
    <% end %>
    <!--<%= form_tag items_path, method: :get, class: 'boards__searchForm' do %>
  　  <%= select_tag :tag_id, options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
    { prompt: 'タグで絞り込み検索',onchange: 'submit(this.form);'}
    %>
    <% end %>-->
  </div>
</div>

app/views/items/_sidebar.html.erb
<div class="sidebar">
<div class="container col-lg-4">
  <div class="sidebar-content well">
    <div class="row" id="side-profile">
      <span class="col-xs-4">
  	    <%= attachment_image_tag current_user, :image, :fill, 40, 40, format: 'jpg',fallback: "no_image.jpg" ,size:'50x50'%>
  	  </span>
      <span class="side-name">
  	    <%= current_user.username %><br>
      </span>
  	</div>

  	<!--<div class="row">
      <span class="col-xs-4">
        投稿数<br>
        <%= current_user.items.count %>
      </span>
      <span class="col-xs-4">
        フォロー<br>
        <%=  %>
      </span>
      <span class="col-xs-4">
        フォロワー<br>
        <%=  %>
      </span>
    </div>-->
    <div class="row">
      <%= link_to '投稿する', new_item_path, class: 'side-btn' %>
    </div>
  </div>
  <div class="sidebar-nav">
    <ul class="nav nav-pills nav-stacked">
      <% if admin_signed_in? %>
        <li class="nav-item"><%= link_to 'ホーム', admins_top_path, class: 'nav-links' %>
        </li>
        <li class="nav-item"><%= link_to '会員一覧', admins_users_path, class: 'nav-links' %>
        </li>
        <li class="nav-item"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-links' %></li>
      <!-- ユーザー -->
      <% elsif user_signed_in? %>
        <p class="text-center">
          <li class="nav-item">
            <%= link_to items_path, class: 'nav-links' do %>
              <i class="fas fa-home"></i>　ホーム
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to user_path(current_user.id), class: 'nav-links' do %>
              <i class="fas fa-user"></i>　マイページ
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to user_about_path, class: 'nav-links' do %>
              <i class="far fa-question-circle"></i>　About
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-links' do %>
              <i class="fas fa-sign-out-alt"></i>　ログアウト
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to contacts_index_path, class: 'nav-links' do %>
              <i class="far fa-envelope"></i>　お問い合わせ
            <% end %>
          </li>
        </p>
        <!-- 非ログイン -->
      <% else %>
        <li class="nav-item"><%= link_to 'About', user_about_path, class: 'nav-links' %>
        </li>
        <li class="nav-item" ><%= link_to '新規登録', new_user_registration_path, class: 'nav-links' %>
        </li>
        <li class="nav-item"><%= link_to 'ログイン', new_user_session_path, class: 'nav-links' %>
        </li>
        <li class="nav-item">
            <%= link_to contacts_index_path, class: 'nav-links' do %>
              <i class="far fa-envelope"></i>　お問い合わせ
            <% end %>
          </li>
      <% end %>
    </ul>
  </div>
</div>
</div>

app/views/items/edit.html.erb
<%= render 'layouts/logo' %>
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<%= render 'layouts/logo' %>
<div class="container">
  <div class="row">
  	<%= render 'items/sidebar' %>
    <div class="main">
  	<div class="col-lg-5">
      <% if @search_items %>
  	  <% @search_items.each do |item|%>
  	    <div class="item-panel">
  	      <div class="item-image">
  	      	<div class="row">
  	      	  <span class="col-xs-3">
  	            <%= link_to user_path(item.user.id) do %>
                <%= attachment_image_tag item.user, :image, :fill, 80, 80, format: 'jpg',fallback: "no_image.jpg" ,size:'80x80'%>
                <% end %>
              </span>
              <span class="col-xs-8">
                <h5 class="item-name"><%= item.user.username %></h5>
              </span>
            </div>
          </div>
          <div class="item-title">
          	<div class="row">
  	      	  <span class="col-xs-3">
  	      	  </span>
  	      	  <span class="col-xs-9">
                <%= link_to item.title, item_path(item) %><br>
              </span>
            </div>
          </div><br>
          <div class="item-text">
          	<div class="row">
  	      	  <span class="col-xs-3">
  	      	  </span>
  	      	  <span class="col-xs-9">
                <%= item.text %><br>
              </span>
            </div>
          </div><br>
          <div class="item-link">
          	<div class="row">
          	  <span class="col-xs-3">
  	      	  </span>
  	      	  <span class="col-xs-2">
  	      	  	<i class="far fa-comments"></i> <%= item.comments.count %>
  	      	  </span>
  	      	  <span class="col-xs-2" id="likes_buttons_<%= item.id %>">
                <!-- <td> -->
                  <%= render partial: "likes/like", locals: { item: item } %>
                <!-- </td> -->
              </span>
              <span class="col-xs-2">
                <%= link_to download_item_path(item), data: { turbolinks: false }, "data-confirm" => "音源をダウンロードしますか？" do %>
                  <i class="fas fa-arrow-alt-circle-down"></i>
                <% end %>
              </span>
              <% if item.user_id == current_user.id %>
              <span class="col-xs-2">
                <%= link_to item_path(item), method: :delete, data: { turbolinks: false }, "data-confirm" => "本当に削除しますか？" do %>
                  <i class="fas fa-trash-alt"></i>
                <% end %>
              </span>
              <% end %>
            </div><br>
            <div class="row">
              <span class="col-xs-3">
              </span>
              <span class="col-xs-9">
                <% item.tags.each do |tag| %>
                  <span class="badge badge-success">
                    <%= tag.name %>
                    <%= audio_tag(item.file) %>
                  </span>
                <% end %>
              </span>
            </div>
          </div>
  	  	</div>
      <% end %>
  	  <% end %>
    </div>
    <%= render 'items/search' %>
  </div>
</div>

app/views/items/new.html.erb
<%= render 'layouts/logo' %>
<div class="container">
  <div class="row">
    <%= render 'items/sidebar' %>
    <div class="main">
      <div class="col-lg-5">
        <%= form_for(@item) do |f|%>
          <div class="form-group">
	          <%= f.label :タイトル %>
            <%= f.text_field :title , class:"form-control" %><br>
            <%= f.label :コメント %>
            <%= f.text_field :text , class:"form-control" %><br>
            <%= f.label :ファイル（wavファイルのみ対応） %>
            <%= f.file_field :file %><br>
            <%= f.label :タグ %><br>
            <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
              <%= tag.label do %>
                <%= tag.check_box %>
                <%= tag.text %>
              <% end %>
            <% end %>
          </div>
          <div>
            <%= f.submit "投稿", data: { turbolinks: false }, class: "f-btn" %>
          </div>
        <% end %>
      </div>
    </div>
    <%= render 'items/search' %>
  </div>
</div>

app/views/items/show.html.erb
<%= render 'layouts/logo' %>
<div class="container">
  <div class="row">
    <%= render 'items/sidebar' %>
    <div class="main">
  	<div class="col-lg-5">
  	  <div class="item-panel-show">
  	    <div class="item-image">
  	      <div class="row">
  	        <span class="col-xs-3">
              <%= link_to user_path(@item.user.id) do %>
              <%= attachment_image_tag @item.user, :image, :fill, 80, 80, format: 'jpg',fallback: "no_image.jpg" ,size:'80x80'%>
              <% end %>
            </span>
            <span class="col-xs-8">
              <h5 class="item-name"><%= @item.user.username %></h5>
            </span>
          </div>
        </div>
        <div class="item-title">
          <div class="row">
  	      	<span class="col-xs-3">
  	      	</span>
  	      	<span class="col-xs-6">
              <%= @item.title %><br>
            </span>
          </div>
        </div><br>
        <div class="item-text">
          <div class="row">
  	        <span class="col-xs-3">
  	      	</span>
  	      	<span class="col-xs-9">
              <%= @item.text %><br>
            </span>
          </div>
        </div><br>
        <div class="item-link">
          <div class="row">
          	<span class="col-xs-3">
  	      	</span>
  	      	<span class="col-xs-8">
  	      	  <%= @item.created_at.strftime("%Y-%m-%d %H:%M") %><br><br />
  	      	</span>
  	      </div>
  	      <div class="row">
  	      	<span class="col-xs-3">
  	      	</span>
  	      	<span class="col-xs-3" id="likes_buttons_<%= @item.id %>">
                <!-- <td> -->
                  <%= render partial: "likes/@like", locals: { item: @item } %>
                <!-- </td> -->
              </span>
            <span class="col-xs-3">
              <%= link_to download_item_path(@item), data: { turbolinks: false }, "data-confirm" => "音源をダウンロードしますか？" do %>
                <i class="fas fa-arrow-alt-circle-down"></i>
              <% end %>
            </span>
            <% if @item.user_id == current_user.id %>
            <span class="col-xs-3">
              <%= link_to item_path(@item), method: :delete, data: { turbolinks: false }, "data-confirm" => "本当に削除しますか？" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </span>
            <% end %>
          </div><br>
          <div class="row">
            <span class="col-xs-3">
            </span>
            <span class="col-xs-9">
              <% @item.tags.each do |tag| %>
                <span class="badge badge-primary">
                  <%= tag.name %>
                </span>
              <% end %>
            </span>
          </div>
        </div>
      </div>
      
      <div class="audio">
        <div class="row">
          <span class="col-xs-3">
            <%= audio_tag(@item.file) %>
          </span>
        </div>
      </div><br><br>

  	  <div class="comment-submit">
      <%= form_for [@item, @comment] do |f| %>
		    <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメント" %><br>
	      <%= f.submit "コメントを送信", class: "c-btn" %><br><br>
	    <% end %>
	    </div>

      <div class="row">
        <% @item.comments.each do |comment| %>
        <div class="comment">
          <div class="comment-image">
            <span class="col-xs-3">
              <%= link_to user_path(comment.user) do %>
                <%= attachment_image_tag comment.user, :image, :fill, 40, 40, format: 'jpg',fallback: "no_image.jpg" ,size:'50x50'%>
              <% end %>
            </span>
            <span class="col-xs-8">
              <h5><%= comment.user.username %></h5>
            </span>
          </div>
          <div class="comment-text">
            <div class="row">
              <span class="col-xs-3">
              </span>
              <span class="col-xs-6">
                <%= comment.comment %>
              </span>
            </div>
          </div><br>
          <div class="comment-delete">
            <div class="row">
              <span class="col-xs-9">
              </span>
              <span class="col-xs-3">
                <% if comment.user_id == current_user.id %>
                  <!--<%= link_to "編集", edit_item_path(@item,comment.id) %>-->
                  <%= link_to "削除", item_comment_path(@item,comment.id), method: :delete %>
                <% end %>
              </span>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    </div>
    <%= render 'items/search' %>
  </div>
</div>



<script>
  audiojs.events.ready(function() {
    var as = audiojs.createAll();
  });
</script>