config/routes.rb
Rails.application.routes.draw do
#rootパス
root 'homes#top'

#userのdevise
devise_for :users, controllers: {
  registrations: 'users/registrations',
  passwords: 'users/passwords',
  sessions: 'users/sessions',
  omniauth_callbacks: 'users/omniauth_callbacks'}

get 'homes/top' => 'homes#top', as: 'user_top'
get 'homes/about' => 'homes#about', as: 'user_about'
resources :users, only: [:show, :edit, :update]
  get 'users/:id/unsubscribe' => 'users#unsubscribe', as: 'user_unsubscribe'
  patch 'users/:id/unsubscribe' => 'users#unsubscribe_done', as: 'user_unsubscribe_done'
  put '/users/:id/unsubscribe' => 'users#unsubscribe_done', as: 'users_unsubscribe_done'

resources :items do
  get 'search' => 'searches#search', as: 'search'
    member do
      get :download
    end
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
end

get  'contacts/index' =>'contacts#index'
post 'contacts/confirm' => 'contacts#confirm'
post 'contacts/done' => 'contacts#done'


# 管理者用サイトのrouting
devise_scope :admins do
	devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    passwords: 'admins/passwords',
    sessions: 'admins/sessions'}
end

namespace :admins do
	get 'homes/top' => 'homes#top', as:'top'
	resources :users, only: [:index, :edit, :show, :update]

    get 'search' => 'searches#search', as: 'search'
end

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :item

	validates :comment, presence: true
end

app/models/contact.rb
class Contact include ActiveModel::Model
    attr_accessor :name, :email, :content

    validates :name, presence: true, length: { maximum: 20 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 30 },
                      format: { with: VALID_EMAIL_REGEX }
    validates :content, presence: true, length: { maximum: 500 }
end

app/models/item.rb
class Item < ApplicationRecord
	mount_uploader :file, AudioFileUploader
	
	belongs_to :user
	has_many :likes, dependent: :destroy
	has_many :comments, dependent: :destroy
  has_many :item_tags, dependent: :destroy
  has_many :tags, through: :item_tags

  validates :title, presence: true
  validates :text, presence: true
  validates :file, presence: true

  default_scope -> { order(created_at: :desc) }

	def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search
      Item.where(['title LIKE ? OR text LIKE ?', "%#{search}%", "%#{search}%"])
    else
      Item.all
    end
  end
end

app/models/item_tag.rb
class ItemTag < ApplicationRecord
  belongs_to :item
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :item

	def liked_by?(user)
      likes.where(user_id: user.id).exists?
    end
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :item_tags, dependent: :destroy
    has_many :items, :through => :item_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  attachment :image

  has_many :items
  has_many :comments
  has_many :likes

  validates :email, presence: true
  validates :name, presence: true
  validates :username, presence: true

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        name:     auth.info.email,
        username: auth.info.email,
        password: Devise.friendly_token[0, 20]
      )
    end

    user
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end

  def top
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def new
    @item = Item.new
  end

  def index
    @items = Item.all
    @item = Item.new
    @search_items = Item.all.page(params[:page]).search(params[:search])
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save!
       redirect_to items_path
    else
       render "new"
    end
  end

  def download
    @item = Item.find(params[:id])
    filepath = "https://rails-item1.s3-ap-northeast-1.amazonaws.com/"+@item.file.current_path
    data = open(URI.encode(filepath))
    send_data data.read, filename: @item.file.identifier, type: "application/wav", disposition: 'inline', stream: 'true', buffer_size: '40960'
  end


  def show
    @item = Item.find(params[:id])
    @newitem = Item.new
    @comment = Comment.new
    @search_items = Item.all.page(params[:page]).search(params[:search])
  end

  def edit
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:id,:user_id,:title,:text,:file,:audio,:serch, { :tag_ids=> [] })
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @item = Item.find(params[:item_id])
  	like = current_user.likes.build(item_id: params[:item_id])
    like.save
  end

  def destroy
    @item = Item.find(params[:item_id])
    like = Like.find_by(item_id: params[:item_id], user_id: current_user.id)
    #binding.pry
  	like.destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user
    before_action :baria_user, only: [:edit,:update,:unsubscribe]


  def edit
  	@user = User.find(params[:id])
  end

  def show
  	@user = User.find(params[:id])
  end

  def unsubscribe
  end

  def update
  	@user = User.find(params[:id])
  	if
  	  @user.update(user_params)
  	  redirect_to user_path(@user.id)
  	else
  	  render "edit"
  	end
  end


private

def set_user
	@user = User.find(params[:id])
end

def user_params
	params.require(:user).permit(:is_status, :name, :username, :image, :uid, :provider, :email, :audio)
end

#url直接防止　メソッドを自己定義してbefore_actionで発動。
  def baria_user
    unless params[:id].to_i == current_user.id
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<header class="container-fluid">
  <nav class="navbar navbar-expand-sm bg-light">
    <!-- ロゴ画像 -->
      <a class="navbar-brand" href="/">session</a>
    <div id="wrapper">
      <p class="btn-gnavi">
        <span></span>
        <span></span>
        <span></span>
      </p>
    <ul class="nav navbar-nav navbar-right">
    <!-- 各種リンク。管理者ログイン時と顧客ログイン時、非ログイン時で表示切替。 -->
      <!-- 管理者 -->
      <% if admin_signed_in? %>
        <li class="nav-item"><%= link_to 'ホーム', admins_top_path, class: 'nav-link' %>
        </li>
        <li class="nav-item"><%= link_to '会員一覧', admins_users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link' %></li>
      <!-- ユーザー -->
      <% elsif user_signed_in? %>
          <li class="nav-item"><%= link_to 'ホーム', items_path, class: 'nav-link' %>
          </li>
          <li class="nav-item"><%= link_to 'About', '#about' %>
          </li>
          <li class="nav-item"><%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link' %>
          </li>
          <li class="nav-item"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
          <li class="nav-item"><%= link_to 'お問い合わせ', contacts_index_path,　class: 'nav-link' %>
          </li>
        <!-- 非ログイン -->
      <% else %>
        <li class="nav-item"><%= link_to 'About', user_about_path, class: 'nav-link' %>
        </li>
        <li class="nav-item" ><%= link_to '新規登録', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item"><%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item"><%= link_to 'お問い合わせ', contacts_index_path,　class: 'nav-link' %>
          </li>
      <% end %>
    </ul>
    </div>
  </nav>

  <a class="nav-button" href="#">
    <span></span>
    <span></span>
    <span></span>
  </a>
</header>

app/views/layouts/_logo.html.erb
<header class="container-fluid">
  <nav class="navbar navbar-expand-sm bg-light">
    <a class="navbar-brand" href="/">session</a>
  </nav>
  <div id="wrapper">
    <p class="btn-gnavi">
      <span></span>
      <span></span>
      <span></span>
    </p>
  </div><br>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Session</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <script type="text/javascript" src="http://api.html5media.info/1.1.4/html5media.min.js"></script>

    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <%= favicon_link_tag %>
    <link rel="icon" type="image/x-icon" href="favicon.ico">
    <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon-180x180.png">
  </head>

  <body>
    <div class="wrap">
      <div class="container-fluid">
    　  <div class="row">
      　  <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>